### ISSUE TITLE
Not showing ALL videos from channel

### ISSUE THREAD

**Issue by dprothero** [warrenbuckley/YouTube-Umbraco#15]
I've been using YouTube-Umbraco successfully for the past couple of weeks. However, today, it started only showing 5 videos in my channel for selection instead of the total 8 videos that are available.

Here is my channel: https://www.youtube.com/channel/UCqiwZNUf9z9OrseJoVGWMMg

As you can see, there are 8 videos there. They were showing up, but now only 5 show up (the missing videos are FEMA Training parts 2, 3, and 6).

I turned on debug and when you select the channel in the data types section, it shows the channel selected and shows there are 8 videos:

![ytu-1](https://cloud.githubusercontent.com/assets/1897006/8338630/f306cfd8-1a66-11e5-9fc4-3353842630c9.png)

However, when editing a document, I can only choose from 5 videos:

![ytu-2](https://cloud.githubusercontent.com/assets/1897006/8338639/01f6d498-1a67-11e5-9890-4e413f49a1b7.png)

As I mentioned at the opening, this was working fine before. Any thoughts on what the issue might be?

**Comment by dprothero** [comment]
Doesn't seem to be an issue with YouTube-Umbraco. I tried this direct API request:

https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=UCqiwZNUf9z9OrseJoVGWMMg&order=date&maxResults=3&type=video&key=[KeyFromSource]

And got the same result (pageInfo.totalResults === 5). I will troubleshoot at the API level and report back if there is anything to report.

**Comment by dprothero** [comment]
http://stackoverflow.com/questions/31035347/youtube-api-v3-search-by-channel-id-not-returning-all-videos-in-the-channel

**Comment by warrenbuckley** [comment]
@dprothero can I close this as it seems a specific problem to the API itself & not the Umbraco Property Editor?

**Comment by Jeavon** [comment]
I believe this is known as Issue 6125 https://code.google.com/p/gdata-issues/issues/detail?id=6125&q=search%20list%20label%3AAPI-YouTube&colspec=API%20ID%20Type%20Status%20Priority%20Stars%20Summary

**Comment by warrenbuckley** [comment]
OK happy for me to close @dprothero & @Jeavon ?

**Comment by Jeavon** [comment]
Yes, it is a YouTube API issue
