### ISSUE TITLE
Youtube Quota reached

### ISSUE THREAD

**Issue by sbozzie** [warrenbuckley/YouTube-Umbraco#19]
```
Google.Apis.Requests.RequestError
The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>. [403]
Errors [
Message[The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.] Location[ - ] Reason[quotaExceeded] Domain[youtube.quota]
]

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Google.GoogleApiException: Google.Apis.Requests.RequestError
The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>. [403]
Errors [
Message[The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.] Location[ - ] Reason[quotaExceeded] Domain[youtube.quota]
]

```

When the Youtube quota is reached, this plugin fails when attempting to find a video:

`foreach (var typedVideo in Model.Content.GetPropertyValue<YouTube>("video").Take(1))`

This causes the page to fail to load.

**Comment by TErenberger** [comment]
We also just started getting this error. Are all instances of this package using the same API key?

**Comment by sbozzie** [comment]
Yes, it seems to be this way - scrabbling a little - does anyone know of a way to supply our own API key for this package? (multiple sites now not displaying videos, and clients are noticing!)

**Comment by PeaWilliams** [comment]
We're also seeing this issue on a client's site.

**Comment by TErenberger** [comment]
https://github.com/warrenbuckley/YouTube-Umbraco/blob/master/YouTube/YouTubeHelper.cs#L12

looks like this is the case

**Comment by mattinkdigital** [comment]
Bump.

**Comment by sbozzie** [comment]
The instructions at https://developers.google.com/youtube/v3/getting-started will help you set up an individual API key. I've rebuilt using one generated, and the issues seem resolved.
It may be worth breaking this API key out into an exposed variable to prevent issues in the future!

**Comment by ryanlewis** [comment]
Resolved in #20

**Comment by ryanlewis** [comment]
If you are looking for a fix right now, AppVeyor just built the package and the artifacts are available [here](https://ci.appveyor.com/project/warrenbuckley/youtube-umbraco/build/1.0.4.81/artifacts).

**Comment by warrenbuckley** [comment]
Thanks awesome Umbraco community 🎉
